from django.urls import reverse_lazy
"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'thfs59l0(kjsurhh#gwg7#2k#7#fbdwh6z+5@j_vtm92kuqm@7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Third Party Apps
    'jet.dashboard',
    'jet',
    # Our Apps
    'cpanel',
    'ai',
    'vezeeta',
    'website',
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "main/template"),
            os.path.join(BASE_DIR, "cpanel/template"),
            os.path.join(BASE_DIR, "ai/template"),
            os.path.join(BASE_DIR, "vezeeta/template"),
            os.path.join(BASE_DIR, "website/template")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'Healthcare',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'USER': 'project',
            'PASSWORD': '74123',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Etc/GMT+2'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "main/static"),
    os.path.join(BASE_DIR, "cpanel/static"),
    os.path.join(BASE_DIR, "ai/static"),
    os.path.join(BASE_DIR, "vezeeta/static"),
    os.path.join(BASE_DIR, "website/static")
]

# To make the static that server manage them
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_root")
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media_root")

AUTH_PROFILE_MODULE = "cpanel.Stakeholders"

# Admin Customization
JET_THEMES = [
    {
        'theme': 'default',  # theme folder name
        'color': '#47bac1',  # color of the theme's button in user menu
        'title': 'Default'  # theme title
    },
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green'
    },
    {
        'theme': 'light-green',
        'color': '#2faa60',
        'title': 'Light Green'
    },
    {
        'theme': 'light-violet',
        'color': '#a464c4',
        'title': 'Light Violet'
    },
    {
        'theme': 'light-blue',
        'color': '#5EADDE',
        'title': 'Light Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]

JET_DEFAULT_THEME = 'default'
JET_SIDE_MENU_COMPACT = True
JET_CHANGE_FORM_SIBLING_LINKS = True
JET_INDEX_DASHBOARD = 'Dashboard.DefaultIndexDashboard'

JET_SIDE_MENU_ITEMS = [  # A list of application or custom item dicts
    {'label': ('administration'), 'app_label': 'auth', 'items': [
        {'label': ('User Profile'), 'url': 'http://127.0.0.1:8000/cpanel/user_profile/', 'url_blank': True},
        {'name': 'auth.user'},
        {'name': 'auth.group'},
        {'name': 'admin.logentry'}
    ]},
    {'label': ('System Panels'), 'app_label': 'pages', 'items': [
        {'label': ('Cpanel'), 'url': 'http://127.0.0.1:8000/cpanel/', 'url_blank': True},
        {'label': ('AI panel'), 'url': 'http://127.0.0.1:8000/ai_panel/', 'url_blank': True},
    ]},
    {'label': ('Applications'), 'app_label': 'cpanel', 'items': [
        {'name': 'cpanel.stakeholders'},
        {'name': 'cpanel.patient'},
        {'name': 'cpanel.physician'},
        {'name': 'cpanel.nurse'},
        {'name': 'cpanel.paramedic'},
        {'name': 'cpanel.specialist'},
        {'name': 'cpanel.pharmacist'},
        {'name': 'cpanel.medicalinstitutions'},
        {'name': 'cpanel.labs'},
        {'name': 'cpanel.clinic'},
        {'name': 'cpanel.pharmacy'},
        {'name': 'cpanel.hospital'},
        {'name': 'cpanel.insurancecompanies'},
        {'name': 'cpanel.specialization'},
        {'name': 'cpanel.patienthistory'},
        {'name': 'cpanel.physicianpatientappointment'},
    ]},
]
