# Generated by Django 2.2.13 on 2020-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vezeeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicianrecommendation',
            name='specialization_id',
            field=models.CharField(db_column='Specialization_ID', max_length=50),
        ),
    ]
