# Generated by Django 2.2.7 on 2020-02-14 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompanies',
            fields=[
                ('company_id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=320, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=25, null=True)),
                ('company_name', models.CharField(blank=True, db_column='Company_Name', max_length=120, null=True)),
                ('company_type', models.CharField(blank=True, db_column='Company_Type', max_length=120, null=True)),
                ('hide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance Company',
                'verbose_name_plural': 'Insurance Companies',
                'db_table': 'insurance_companies',
            },
        ),
        migrations.CreateModel(
            name='InsuranceTypes',
            fields=[
                ('type_id', models.AutoField(db_column='Type_ID', primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, db_column='Type_Name', max_length=120, null=True)),
                ('hide', models.BooleanField(default=False)),
                ('company', models.ForeignKey(db_column='Company_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.InsuranceCompanies')),
            ],
            options={
                'verbose_name': 'Insurance Type',
                'verbose_name_plural': 'Insurance Types',
                'db_table': 'insurance_types',
                'unique_together': {('type_name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='MedicalInstitutions',
            fields=[
                ('institution_id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, db_column='Image', null=True, upload_to='Medical_Institutions/images')),
                ('institution_name', models.CharField(blank=True, db_column='Institution_Name', max_length=120, null=True)),
                ('hide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Institution',
                'verbose_name_plural': 'Medical Institutions',
                'db_table': 'medical_institutions',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='Stakeholders',
            fields=[
                ('national_number', models.CharField(db_column='National_Number', max_length=20, primary_key=True, serialize=False)),
                ('stakeholder_name', models.CharField(blank=True, db_column='Stakeholder_Name', max_length=255, null=True)),
                ('stakeholder_last_name', models.CharField(blank=True, db_column='Stakeholder_Last_Name', max_length=255, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, db_column='Birthday', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], db_column='Gender', max_length=6, null=True)),
                ('stakeholder_type', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Clerk', 'Clerk'), ('Editors', 'Editors')], db_column='Stakeholder_Type', max_length=10, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=320, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widow', 'Widow'), ('Divorced', 'Divorced')], db_column='Marital_Status', max_length=8, null=True)),
                ('image', models.ImageField(blank=True, db_column='Image', default=None, null=True, upload_to='Stakeholder/images')),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=255, null=True)),
                ('cv', models.CharField(blank=True, db_column='cv', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hide', models.BooleanField(default=False)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
                'db_table': 'stakeholders',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic', models.OneToOneField(db_column='Clinic_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.MedicalInstitutions')),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=25, null=True)),
                ('er_availability', models.BooleanField(blank=True, db_column='ER_Availability', null=True)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'db_table': 'clinic',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital', models.OneToOneField(db_column='Hospital_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.MedicalInstitutions')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=320, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=25, null=True)),
                ('er_availability', models.BooleanField(blank=True, db_column='ER_Availability', null=True)),
                ('hospital_type', models.CharField(blank=True, db_column='Hospital_type', max_length=120, null=True)),
                ('manager', models.CharField(blank=True, max_length=60, null=True)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('lab', models.OneToOneField(db_column='Lab_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.MedicalInstitutions')),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=25, null=True)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
                'db_table': 'labs',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nurse_nn', models.OneToOneField(db_column='Nurse_NN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.Stakeholders')),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nurse',
                'verbose_name_plural': 'Nurses',
                'db_table': 'nurse',
            },
        ),
        migrations.CreateModel(
            name='Paramedic',
            fields=[
                ('paramedic_nn', models.OneToOneField(db_column='Paramedic_NN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.Stakeholders')),
                ('ambulance_palte_number', models.CharField(blank=True, db_column='Ambulance_Palte_number', max_length=12, null=True)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Paramedic',
                'verbose_name_plural': 'Paramedics',
                'db_table': 'paramedic',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_nn', models.OneToOneField(db_column='Patient_NN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.Stakeholders')),
                ('chronic_diseases_name', models.CharField(blank=True, db_column='Chronic_Diseases_Name', max_length=255, null=True)),
                ('chronic_diseases_type', models.CharField(blank=True, db_column='Chronic_Diseases_Type', max_length=255, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], db_column='Blood_Type', max_length=3, null=True)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('pharmacist_nn', models.OneToOneField(db_column='Pharmacist_NN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.Stakeholders')),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pharmacist',
                'verbose_name_plural': 'Pharmacists',
                'db_table': 'pharmacist',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy', models.OneToOneField(db_column='Pharmacy_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.MedicalInstitutions')),
                ('pharmacy_type', models.CharField(blank=True, db_column='Pharmacy_Type', max_length=120, null=True)),
                ('hide', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(db_column='Owner', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Pharmacist')),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
                'db_table': 'pharmacy',
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('physician_nn', models.OneToOneField(db_column='Physician_NN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.Stakeholders')),
                ('rate', models.FloatField(blank=True, db_column='Rate', null=True)),
                ('title', models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Lecturer', 'Lecturer'), ('Consultant', 'Consultant'), ('Specialist', 'Specialist')], db_column='Title', max_length=10, null=True)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Physician',
                'verbose_name_plural': 'Physicians',
                'db_table': 'physician',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('specialist_nn', models.OneToOneField(db_column='Specialist_NN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cpanel.Stakeholders')),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Specialist',
                'verbose_name_plural': 'Specialists',
                'db_table': 'specialist',
            },
        ),
        migrations.CreateModel(
            name='StakeholdersPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_column='Phone', max_length=25)),
                ('national_number', models.ForeignKey(db_column='National_Number', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Stakeholders')),
            ],
            options={
                'verbose_name': 'Stakeholders Phone',
                'verbose_name_plural': 'Stakeholders Phones',
                'db_table': 'stakeholders_phones',
                'unique_together': {('national_number', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='StakeholdersAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_column='Address', max_length=360)),
                ('national_number', models.ForeignKey(db_column='National_Number', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Stakeholders')),
            ],
            options={
                'verbose_name': 'Stakeholders Address',
                'verbose_name_plural': 'Stakeholders Addresses',
                'db_table': 'stakeholders_address',
                'unique_together': {('national_number', 'address')},
            },
        ),
        migrations.CreateModel(
            name='MedicalInstitutionsPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_column='Phone', max_length=25)),
                ('institution', models.ForeignKey(db_column='Institution_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.MedicalInstitutions')),
            ],
            options={
                'verbose_name': 'Medical Institution Phone',
                'verbose_name_plural': 'Medical Institution Phones',
                'db_table': 'medical_institutions_phone',
                'unique_together': {('institution', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='MedicalInstitutionsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_column='Adress', max_length=360)),
                ('institution', models.ForeignKey(db_column='Institution_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.MedicalInstitutions')),
            ],
            options={
                'verbose_name': 'Medical Institution Address',
                'verbose_name_plural': 'Medical Institution Addresses',
                'db_table': 'medical_institutions_adress',
                'unique_together': {('institution', 'address')},
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompaniesPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_column='Phone', max_length=25)),
                ('company', models.ForeignKey(db_column='Company_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.InsuranceCompanies')),
            ],
            options={
                'verbose_name': 'Insurance Company Phone',
                'verbose_name_plural': 'Insurance Company Phones',
                'db_table': 'insurance_companies_phone',
                'unique_together': {('company', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompaniesAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_column='Address', max_length=360)),
                ('company', models.ForeignKey(db_column='Company_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.InsuranceCompanies')),
            ],
            options={
                'verbose_name': 'Insurance Company Address',
                'verbose_name_plural': 'Insurance Company Addresses',
                'db_table': 'insurance_companies_address',
                'unique_together': {('company', 'address')},
            },
        ),
        migrations.CreateModel(
            name='SpecialistSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(db_column='Specialization', max_length=120)),
                ('specialist_nn', models.ForeignKey(db_column='Specialist_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Specialist')),
            ],
            options={
                'verbose_name': 'Specialist Specialization',
                'verbose_name_plural': 'Specialist Specializations',
                'db_table': 'specialist_specialization',
                'unique_together': {('specialist_nn', 'specialization')},
            },
        ),
        migrations.CreateModel(
            name='PhysicianSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(db_column='Specialization_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Specialization')),
                ('physician_nn', models.ForeignKey(db_column='Physician_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Physician')),
            ],
            options={
                'verbose_name': 'Physician Specialization',
                'verbose_name_plural': 'Physician Specializations',
                'db_table': 'physician_specialization',
                'unique_together': {('physician_nn', 'specialization')},
            },
        ),
        migrations.CreateModel(
            name='PhysicianRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_comment', models.TextField(blank=True, db_column='Patient_comment', null=True)),
                ('patient_nn', models.ForeignKey(db_column='Patient_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Patient')),
                ('physician_nn', models.ForeignKey(db_column='Physician_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Physician')),
            ],
            options={
                'verbose_name': 'Physician Rating',
                'verbose_name_plural': 'Physician Ratings',
                'db_table': 'physician_rating',
                'unique_together': {('patient_nn', 'physician_nn')},
            },
        ),
        migrations.CreateModel(
            name='PhysicianPatientAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(db_column='Date_Time')),
                ('place', models.CharField(blank=True, db_column='Place', max_length=120, null=True)),
                ('patient_nn', models.ForeignKey(db_column='Patient_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Patient')),
                ('physician_nn', models.ForeignKey(db_column='Physician_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Physician')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'physician_patient_appointment',
                'unique_together': {('patient_nn', 'physician_nn', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='PhysicianHospitalWorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], db_column='Week_Day', max_length=9)),
                ('start_time', models.TimeField(db_column='Start_Time')),
                ('end_time', models.TimeField(db_column='End_Time')),
                ('fee', models.IntegerField(blank=True, db_column='Fee', null=True)),
                ('hide', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(db_column='Hospital_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Hospital')),
                ('physician_nn', models.ForeignKey(db_column='Physician_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Physician')),
            ],
            options={
                'verbose_name': 'Physician Hospital Working Time',
                'verbose_name_plural': 'Physician Hospital Working Times',
                'db_table': 'physician_hospital_working_time',
                'unique_together': {('physician_nn', 'hospital', 'week_day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='PhysicianClinicWorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], db_column='Week_Day', max_length=9)),
                ('start_time', models.TimeField(db_column='Start_Time')),
                ('end_time', models.TimeField(db_column='End_Time')),
                ('fee', models.IntegerField(blank=True, db_column='Fee', null=True)),
                ('hide', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(db_column='Clinic_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Clinic')),
                ('physician_nn', models.ForeignKey(db_column='Physician_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Physician')),
            ],
            options={
                'verbose_name': 'Physician Clinic Working Time',
                'verbose_name_plural': 'Physician Clinic Working Times',
                'db_table': 'physician_clinic_working_time',
                'unique_together': {('physician_nn', 'clinic', 'week_day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='PharmacyPharmacists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacist_nn', models.ForeignKey(db_column='Pharmacist_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Pharmacist')),
                ('pharmacy', models.ForeignKey(db_column='Pharmacy_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Pharmacy')),
            ],
            options={
                'verbose_name': 'Pharmacy Specialist',
                'verbose_name_plural': 'Pharmacy Specialists',
                'db_table': 'pharmacy_pharmacists',
                'unique_together': {('pharmacy', 'pharmacist_nn')},
            },
        ),
        migrations.CreateModel(
            name='PharmacyInsuranceDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(blank=True, null=True)),
                ('insurance_type', models.ForeignKey(db_column='Insurance_Type_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.InsuranceTypes')),
                ('pharmacy', models.ForeignKey(db_column='Pharmacy_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Pharmacy')),
            ],
            options={
                'verbose_name': 'Pharmacy Insurance Deal',
                'verbose_name_plural': 'Pharmacies Insurance Deals',
                'db_table': 'pharmacy_insurance_deals',
                'unique_together': {('pharmacy', 'insurance_type')},
            },
        ),
        migrations.CreateModel(
            name='PharmacistSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(db_column='Specialization', max_length=120)),
                ('pharmacist_nn', models.ForeignKey(db_column='Pharmacist_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Pharmacist')),
            ],
            options={
                'verbose_name': 'Pharmacist Specialization',
                'verbose_name_plural': 'Pharmacist Specializations',
                'db_table': 'pharmacist_specialization',
                'unique_together': {('pharmacist_nn', 'specialization')},
            },
        ),
        migrations.CreateModel(
            name='PatientRelativesPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_column='Phone', max_length=25)),
                ('patient_nn', models.ForeignKey(db_column='Patient_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Patient')),
            ],
            options={
                'verbose_name': 'Patient Relatives Phone',
                'verbose_name_plural': 'Patient Relatives Phones',
                'db_table': 'patient_relatives_phones',
                'unique_together': {('patient_nn', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type_id', models.IntegerField(db_column='Insurance_Type_ID')),
                ('patient_nn', models.ForeignKey(db_column='Patient_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Patient')),
            ],
            options={
                'verbose_name': 'Patient Insurance',
                'verbose_name_plural': 'Patient Insurances',
                'db_table': 'patient_insurance',
                'unique_together': {('patient_nn', 'insurance_type_id')},
            },
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(db_column='Date_Time')),
                ('visitation_type', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Consultation', 'Consultation'), ('Operation', 'Operation'), ('ER', 'ER'), ('Other', 'Other')], db_column='Visitation_Type', max_length=12, null=True)),
                ('prescription', models.TextField(blank=True, db_column='Prescription', null=True)),
                ('physician_comments', models.TextField(blank=True, db_column='Physician_Comments', null=True)),
                ('diagnouse', models.CharField(blank=True, db_column='Diagnouse', max_length=360, null=True)),
                ('analysis_radiology', models.CharField(blank=True, db_column='Analysis_Radiology', max_length=360, null=True)),
                ('disease_priority', models.CharField(blank=True, choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_column='Disease_Priority', max_length=9, null=True)),
                ('hide', models.BooleanField(default=False)),
                ('patient_nn', models.ForeignKey(db_column='Patient_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Patient')),
                ('physician_nn', models.ForeignKey(db_column='Physician_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Physician')),
            ],
            options={
                'verbose_name': 'Patient History',
                'verbose_name_plural': 'Patients History',
                'db_table': 'patient_history',
                'unique_together': {('patient_nn', 'physician_nn', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='NurseSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(db_column='Specialization', max_length=120)),
                ('nurse_nn', models.ForeignKey(db_column='Nurse_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Nurse')),
            ],
            options={
                'verbose_name': 'Nurse Specialization',
                'verbose_name_plural': 'Nurse Specializations',
                'db_table': 'nurse_specialization',
                'unique_together': {('nurse_nn', 'specialization')},
            },
        ),
        migrations.CreateModel(
            name='LabSpecialists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(db_column='Lab_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Labs')),
                ('specialist_nn', models.ForeignKey(db_column='Specialist_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Specialist')),
            ],
            options={
                'verbose_name': 'Lab Specialist',
                'verbose_name_plural': 'Lab Specialists',
                'db_table': 'lab_specialists',
                'unique_together': {('lab', 'specialist_nn')},
            },
        ),
        migrations.CreateModel(
            name='LabsInsuranceDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(blank=True, null=True)),
                ('insurance_type', models.ForeignKey(db_column='Insurance_Type_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.InsuranceTypes')),
                ('lab', models.ForeignKey(db_column='Lab_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Labs')),
            ],
            options={
                'verbose_name': 'Lab Insurance Deal',
                'verbose_name_plural': 'Labs Insurance Deals',
                'db_table': 'labs_insurance_deals',
                'unique_together': {('lab', 'insurance_type')},
            },
        ),
        migrations.CreateModel(
            name='LabsAnalysisAndRadiology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_and_radiology', models.CharField(db_column='Analysis_And_Radiology', max_length=25)),
                ('lab', models.ForeignKey(db_column='Lab_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Labs')),
            ],
            options={
                'verbose_name': 'Lab Analysis And Radiology',
                'verbose_name_plural': 'Labs Analysis And Radiology',
                'db_table': 'labs_analysis_and_radiology',
                'unique_together': {('lab', 'analysis_and_radiology')},
            },
        ),
        migrations.CreateModel(
            name='LabRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_comment', models.TextField(blank=True, db_column='Patient_comment', null=True)),
                ('lab', models.ForeignKey(db_column='Lab_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Labs')),
                ('patient_nn', models.ForeignKey(db_column='Patient_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Patient')),
            ],
            options={
                'verbose_name': 'Lab Rating',
                'verbose_name_plural': 'Lab Ratings',
                'db_table': 'lab_rating',
                'unique_together': {('patient_nn', 'lab')},
            },
        ),
        migrations.CreateModel(
            name='LabNurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(db_column='Lab_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Labs')),
                ('nurse_nn', models.ForeignKey(db_column='Nurse_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Nurse')),
            ],
            options={
                'verbose_name': 'Lab Nurse',
                'verbose_name_plural': 'Lab Nurses',
                'db_table': 'lab_nurses',
                'unique_together': {('lab', 'nurse_nn')},
            },
        ),
        migrations.CreateModel(
            name='HospitalSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(db_column='Specialization_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Specialization')),
                ('hospital', models.ForeignKey(db_column='Hospital_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Hospital')),
            ],
            options={
                'verbose_name': 'Hospital Specialization',
                'verbose_name_plural': 'Hospital Specializations',
                'db_table': 'hospital_specialization',
                'unique_together': {('hospital', 'specialization')},
            },
        ),
        migrations.CreateModel(
            name='HospitalSpecialists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(db_column='Hospital_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Hospital')),
                ('specialist_nn', models.ForeignKey(db_column='Specialist_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Specialist')),
            ],
            options={
                'verbose_name': 'Hospital Specialist',
                'verbose_name_plural': 'Hospital Specialists',
                'db_table': 'hospital_specialists',
                'unique_together': {('hospital', 'specialist_nn')},
            },
        ),
        migrations.CreateModel(
            name='HospitalRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_comment', models.TextField(blank=True, db_column='Patient_comment', null=True)),
                ('hospital', models.ForeignKey(db_column='Hospital_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Hospital')),
                ('patient_nn', models.ForeignKey(db_column='Patient_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Patient')),
            ],
            options={
                'verbose_name': 'Hospital Rating',
                'verbose_name_plural': 'Hospital Ratings',
                'db_table': 'hospital_rating',
                'unique_together': {('patient_nn', 'hospital')},
            },
        ),
        migrations.CreateModel(
            name='HospitalNurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(db_column='Hospital_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Hospital')),
                ('nurse_nn', models.ForeignKey(db_column='Nurse_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Nurse')),
            ],
            options={
                'verbose_name': 'Hospital Nurse',
                'verbose_name_plural': 'Hospital Nurses',
                'db_table': 'hospital_nurses',
                'unique_together': {('hospital', 'nurse_nn')},
            },
        ),
        migrations.CreateModel(
            name='HospitalInsuranceDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(blank=True, null=True)),
                ('insurance_type', models.ForeignKey(db_column='Insurance_Type_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.InsuranceTypes')),
                ('hospital', models.ForeignKey(db_column='Hospital_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Hospital')),
            ],
            options={
                'verbose_name': 'Hospital Insurance Deal',
                'verbose_name_plural': 'Hospitals Insurance Deals',
                'db_table': 'hospital_insurance_deals',
                'unique_together': {('hospital', 'insurance_type')},
            },
        ),
        migrations.CreateModel(
            name='ClinicSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(db_column='Specialization_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Specialization')),
                ('clinic', models.ForeignKey(db_column='Clinic_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Clinic')),
            ],
            options={
                'verbose_name': 'Clinic Specialization',
                'verbose_name_plural': 'Clinic Specializations',
                'db_table': 'clinic_specialization',
                'unique_together': {('clinic', 'specialization')},
            },
        ),
        migrations.CreateModel(
            name='ClinicSpecialists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(db_column='Clinic_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Clinic')),
                ('specialist_nn', models.ForeignKey(db_column='Specialist_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Specialist')),
            ],
            options={
                'verbose_name': 'Clinic Specialist',
                'verbose_name_plural': 'Clinic Specialists',
                'db_table': 'clinic_specialists',
                'unique_together': {('clinic', 'specialist_nn')},
            },
        ),
        migrations.CreateModel(
            name='ClinicsInsuranceDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(blank=True, null=True)),
                ('insurance_type', models.ForeignKey(db_column='Insurance_Type_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.InsuranceTypes')),
                ('clinic', models.ForeignKey(db_column='Clinic_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Clinic')),
            ],
            options={
                'verbose_name': 'Clinic Insurance Deal',
                'verbose_name_plural': 'Clinics Insurance Deals',
                'db_table': 'clinics_insurance_deals',
                'unique_together': {('clinic', 'insurance_type')},
            },
        ),
        migrations.CreateModel(
            name='ClinicRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_comment', models.TextField(blank=True, db_column='Patient_comment', null=True)),
                ('clinic', models.ForeignKey(db_column='Clinic_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Clinic')),
                ('patient_nn', models.ForeignKey(db_column='Patient_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Patient')),
            ],
            options={
                'verbose_name': 'Clinic Rating',
                'verbose_name_plural': 'Clinic Ratings',
                'db_table': 'clinic_rating',
                'unique_together': {('patient_nn', 'clinic')},
            },
        ),
        migrations.CreateModel(
            name='ClinicNurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(db_column='Clinic_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Clinic')),
                ('nurse_nn', models.ForeignKey(db_column='Nurse_NN', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Nurse')),
            ],
            options={
                'verbose_name': 'Clinic Nurse',
                'verbose_name_plural': 'Clinic Nurses',
                'db_table': 'clinic_nurses',
                'unique_together': {('clinic', 'nurse_nn')},
            },
        ),
    ]
