# Generated by Django 2.2.13 on 2020-06-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='analysis_radiology',
            field=models.TextField(blank=True, db_column='Analysis_Radiology', null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='diagnouse',
            field=models.TextField(blank=True, db_column='Diagnouse', null=True),
        ),
    ]
