# Generated by Django 2.2.7 on 2020-02-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholders',
            name='password',
        ),
        migrations.AlterField(
            model_name='nursespecialization',
            name='specialization',
            field=models.ForeignKey(db_column='Specialization_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='cpanel.Specialization'),
        ),
        migrations.AlterField(
            model_name='stakeholders',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', default='avatar.jpg', null=True, upload_to='Stakeholder/images'),
        ),
    ]
