# Generated by Django 2.2.13 on 2020-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0002_auto_20200609_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicianpatientappointment',
            name='place',
            field=models.CharField(blank=True, db_column='Place', max_length=360, null=True),
        ),
    ]
