# Generated by Django 2.2.7 on 2020-05-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0002_auto_20200220_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinstitutions',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', default='image.png', null=True, upload_to='Medical_Institutions/images'),
        ),
    ]
