# Generated by Django 2.2.13 on 2020-06-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0004_physicianrating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicianrating',
            name='rate',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1),
        ),
    ]
