# Generated by Django 2.2.13 on 2020-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0006_auto_20200609_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicrating',
            name='rate',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalrating',
            name='rate',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labrating',
            name='rate',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
